apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: spotify
  name: spotify-api-ing
spec:
  tls:
  - hosts:
    - spotifyapi.cescoferraro.xyz
    secretName: wildcard-tls
  rules:
  - host: spotifyapi.cescoferraro.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: spotify-api-svc
          servicePort: 8080
