language: go
dist: bionic
services:
  - docker
node_js: "13"
before_script:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - docker info
  - nvm install 13
  - yarn
script:
  - yarn build
  - bash scripts/buildGO.sh
  - docker-compose stop web
  - docker-compose rm -f web
  - docker-compose up --build web

#env:
#  - DOCKER_HOST="ssh://root@45.79.80.53"

