language: go
dist: bionic
services:
  - docker
node_js: "13"
before_script:
  - nvm install 13
  - yarn
script:
  - yarn build
  - bash scripts/buildGO.sh
  - docker-compose stop web
  - docker-compose rm -f web
  - docker-compose up --build web

env:
  - DOCKER_HOST="ssh://root@45.79.80.53"

