version: '3.2'
services:
  web:
    container_name: web_spotify
    build:
      context: ./build
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=spotify.cescoferraro.xyz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=spotify.cescoferraro.xyz
      - LETSENCRYPT_EMAIL=francescoaferraro@gmail.com
    networks:
      global:
  api:
    container_name: api
    build:
      context: ./dist
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=spotifyapi.cescoferraro.xyz
      - VIRTUAL_PORT=8080
      - KUBERNETES=true
      - LETSENCRYPT_HOST=spotifyapi.cescoferraro.xyz
      - LETSENCRYPT_EMAIL=francescoaferraro@gmail.com
    networks:
      global:
networks:
  global:
    external: true
