version: '3'
services:
  nginx:
    image: cescoferraro/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  api:
    container_name: api
    build:
      context: ./api/dist
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=spotifyapi.cescoferraro.xyz
      #      - CERT_NAME=shared
      - KUBERNETES=true
